# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0009_remove_feature_user_detail'),
        ('changeset', '0029_suspiciousfeature_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='suspicionscore',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='suspicionscore',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='suspiciousfeature',
            name='changeset',
        ),
        migrations.RemoveField(
            model_name='suspiciousfeature',
            name='reasons',
        ),
        migrations.AlterUniqueTogether(
            name='usersuspicionscore',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='usersuspicionscore',
            name='user',
        ),
        migrations.RemoveField(
            model_name='changeset',
            name='user_detail',
        ),
        migrations.DeleteModel(
            name='SuspicionScore',
        ),
        migrations.DeleteModel(
            name='SuspiciousFeature',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
        migrations.DeleteModel(
            name='UserSuspicionScore',
        ),
    ]
