# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-01 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0030_auto_20170201_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeset',
            name='score',
        ),
    ]
