# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 00:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0031_remove_changeset_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='bbox',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='checked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='comment',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='editor',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='harmful',
            field=models.NullBooleanField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userwhitelist',
            name='whitelist_user',
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
