# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0032_auto_20170210_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicionreasons',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
