# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0035_auto_20170224_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarmfulReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('is_visible', models.BooleanField(default=True)),
                ('available_to_changeset', models.BooleanField(default=True)),
                ('available_to_feature', models.BooleanField(default=True)),
            ],
        ),
    ]
