# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0036_harmfulreason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harmfulreason',
            old_name='available_to_changeset',
            new_name='for_changeset',
        ),
        migrations.RenameField(
            model_name='harmfulreason',
            old_name='available_to_feature',
            new_name='for_feature',
        ),
        migrations.RenameField(
            model_name='suspicionreasons',
            old_name='available_to_changeset',
            new_name='for_changeset',
        ),
        migrations.RenameField(
            model_name='suspicionreasons',
            old_name='available_to_feature',
            new_name='for_feature',
        ),
    ]
