# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0037_auto_20170224_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='harmful_reasons',
            field=models.ManyToManyField(related_name='changesets', to='changeset.HarmfulReason'),
        ),
    ]
