# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 02:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0038_changeset_harmful_reasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suspicionreasons',
            options={'verbose_name': 'Suspicion reason', 'verbose_name_plural': 'Suspicion reasons'},
        ),
    ]
