# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0039_auto_20170301_0236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeset',
            options={'ordering': ['-id']},
        ),
    ]
