
# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 11:45
from __future__ import unicode_literals

from django.db import migrations


def merge_suspicionreasons(apps, schema_editor):
    SuspicionReasons = apps.get_model('changeset', 'SuspicionReasons')
    distinct_reasons = SuspicionReasons.objects.all().distinct('name')
    for reason in distinct_reasons:
        same_reasons = SuspicionReasons.objects.filter(name=reason.name).exclude(pk=reason.pk)
        if same_reasons.count() > 0:
            for same_reason in same_reasons:
                changesets = same_reason.changesets.all()
                features = same_reason.features.all()
                for c in changesets:
                    c.reasons.remove(same_reason)
                    c.reasons.add(reason)
                for f in features:
                    f.reasons.remove(same_reason)
                    f.reasons.add(reason)
                print("deleting %s" % same_reason.name)
                same_reason.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0039_auto_20170301_0236'),
    ]

    operations = [
        migrations.RunPython(merge_suspicionreasons, reverse_code=migrations.RunPython.noop),
]
