# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0040_auto_20170311_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwhitelist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelists', to=settings.AUTH_USER_MODEL),
        ),
    ]
