# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0041_auto_20170317_0238'),
        ('changeset', '0041_auto_20170328_1352'),
    ]

    operations = [
    ]
