# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0044_merge_20170330_1409'),
        ('feature', '0012_feature_harmful_reasons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HarmfulReason',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='changeset',
            old_name='harmful_reasons',
            new_name='tags',
        ),
    ]
