# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-14 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0045_auto_20170410_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='uid',
            field=models.CharField(db_index=True, max_length=255, verbose_name='User ID'),
        ),
    ]
