# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0046_auto_20170414_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='imagery_used',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='suspicionreasons',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='is_visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
