# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0047_auto_20170417_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
