# Generated by Django 2.0.6 on 2018-10-08 10:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0049_auto_20180307_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='new_features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='uid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='User ID'),
        ),
    ]
