# Generated by Django 2.2.13 on 2020-08-04 09:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0050_auto_20181008_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
