# Generated by Django 2.2.13 on 2020-09-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0051_changeset_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='comments_count',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
