# Generated by Django 2.0.6 on 2018-08-15 21:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0051_auto_20180809_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='new_features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
