# Generated by Django 2.2.13 on 2020-11-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0052_changeset_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeset',
            name='comments_count',
            field=models.IntegerField(db_index=True, default=0, null=True),
        ),
    ]
