# Generated by Django 2.2.20 on 2021-05-06 11:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0053_auto_20201105_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='reviewed_features',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
