# Generated by Django 2.2.25 on 2022-02-24 15:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0054_changeset_reviewed_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeset',
            name='tag_changes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
