# Generated by Django 2.2.27 on 2022-04-29 13:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0055_changeset_tag_changes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='changeset',
            index=django.contrib.postgres.indexes.GinIndex(fields=['tag_changes'], name='changeset_c_tag_cha_0e8c71_gin'),
        ),
    ]
