# Generated by Django 5.2.8 on 2026-01-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0057_auto_20220920_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changeset',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='changeset',
            name='harmful',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='new_features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='reviewed_features',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='changeset',
            name='tag_changes',
            field=models.JSONField(default=dict),
        ),
    ]
