# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 06:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0003_auto_20161017_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='oldGeojson',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='oldGeometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
