# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 05:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0004_auto_20161019_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
