# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_feature_osm_compare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='osm_compare',
        ),
        migrations.AddField(
            model_name='feature',
            name='comparator_version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
