# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0005_auto_20161114_0543'),
        ('feature', '0006_auto_20161026_1323'),
    ]

    operations = [
    ]
