# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-24 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0007_merge_20161122_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='osm_id',
            field=models.BigIntegerField(),
        ),
    ]
