# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0009_remove_feature_user_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='oldGeojson',
            new_name='old_geojson',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='oldGeometry',
            new_name='old_geometry',
        ),
    ]
