# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-07 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0010_auto_20170207_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='score',
        ),
    ]
