# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeset', '0038_changeset_harmful_reasons'),
        ('feature', '0011_remove_feature_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='harmful_reasons',
            field=models.ManyToManyField(related_name='features', to='changeset.HarmfulReason'),
        ),
    ]
