# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0012_feature_harmful_reasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-changeset_id']},
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='harmful_reasons',
            new_name='tags',
        ),
    ]
