# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 17:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0013_auto_20170410_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='check_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='checked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='feature',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='feature',
            name='harmful',
            field=models.NullBooleanField(db_index=True),
        ),
    ]
