# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0014_auto_20170417_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='changeset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='changeset.Changeset'),
        ),
    ]
