# Generated by Django 2.0.3 on 2018-03-07 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0015_auto_20170421_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='check_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
