# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-30 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20151124_0124'),
        ('users', '0002_auto_20161005_1234'),
    ]

    operations = [
    ]
