# Generated by Django 2.0.3 on 2018-03-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180118_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='comment_feature',
            field=models.BooleanField(default=False, verbose_name='Enable suggestion to post comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
    ]
