# Generated by Django 2.0.9 on 2019-01-23 11:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180307_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('trusted', models.BooleanField(default=False)),
                ('users', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mapping Team',
                'verbose_name_plural': 'Mapping Teams',
                'ordering': ['date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='mappingteam',
            unique_together={('created_by', 'name')},
        ),
    ]
