# Generated by Django 2.2.28 on 2024-05-23 02:27

from django.db import migrations


def update_provider(apps, schema_editor):
    # To keep the same users entries we have right now in the database,
    # we need to update the UserSocialAuth entries' providers
    UserSocialAuth = apps.get_model("social_django", "UserSocialAuth")
    UserSocialAuth.objects.all().update(provider="openstreetmap-oauth2")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190206_1257'),
    ]

    operations = [
        migrations.RunPython(update_provider),
    ]
