# Generated by Django 5.2.8 on 2026-01-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20240523_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappingteam',
            name='users',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
