# Generated by Django 5.2.8 on 2026-01-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_merge_20170130_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['domain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
