# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervise', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='areaofinterest',
            unique_together=set([('user', 'name')]),
        ),
    ]
