# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0003_auto_20170227_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaofinterest',
            old_name='place',
            new_name='geometry',
        ),
    ]
