# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0004_auto_20170405_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areaofinterest',
            name='id',
        ),
        migrations.AddField(
            model_name='areaofinterest',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
