# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0005_auto_20170405_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaofinterest',
            old_name='uuid',
            new_name='id',
        ),
    ]
