# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 21:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0006_auto_20170405_2328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofinterest',
            options={'verbose_name': 'Area of Interest', 'verbose_name_plural': 'Areas of Interest'},
        ),
        migrations.AlterField(
            model_name='areaofinterest',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
