# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 21:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0007_auto_20170504_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofinterest',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'in_bbox': '-180,-180,180,180'}),
            preserve_default=False,
        ),
    ]
