# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0009_blacklisteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofinterest',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
