# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0010_areaofinterest_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areaofinterest',
            options={'ordering': ['-date'], 'verbose_name': 'Area of Interest', 'verbose_name_plural': 'Areas of Interest'},
        ),
        migrations.AddField(
            model_name='blacklisteduser',
            name='uid',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blacklisteduser',
            name='username',
            field=models.CharField(max_length=1000),
        ),
    ]
