# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0012_populate_uid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisteduser',
            name='uid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
