# Generated by Django 2.0.3 on 2018-03-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0013_auto_20170720_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blacklisteduser',
            options={'ordering': ['-date']},
        ),
    ]
