# Generated by Django 2.0.9 on 2018-11-29 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supervise', '0014_auto_20180307_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklisteduser',
            name='uid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='blacklisteduser',
            unique_together={('uid', 'added_by')},
        ),
    ]
