# Generated by Django 5.2.8 on 2026-01-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervise', '0015_auto_20181129_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofinterest',
            name='filters',
            field=models.JSONField(),
        ),
    ]
